### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlexHedley**
Formatted README

### CODE REVIEW

**Comment by AlexHedley** [comment]
@ConstiF are there any updates needed before this could be merged?

**Comment by ConstiF** [comment]
Alex

There was an update to the readme.md document on 3/15 to include
documentation for a new script cwpasset_agent_status.py. You may check the
history to get more details.
May I know what edits you had made to Readme doc?

Are you actively using any of the Python or Powershell samples to develop
on your own automation scripts?

**Comment by AlexHedley** [comment]
I've added some formatting to make the commands a little easier to read,

We've been using the `cwpagentinstall.py` amongst others, for some deployments.

**Review by ConstiF — APPROVED** [review]

**Comment by ConstiF** [comment]
Changes approved. Alex - appreciate your contribution.

**Comment by AlexHedley** [comment]
Thanks, who is able to merge? I'd need write access to the Repo to do it myself, so can't.

**Comment by ConstiF** [comment]
Alex. I'll give you access. Do add any additional REST client code samples
if you build any.

**Comment by AlexHedley** [comment]
Will do :-)

**Pull request merged**
